version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.12.3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install flake8

      - run:
          name: run linting
          command: |
            . venv/bin/activate
            flake8 --max-line-length=100 ~/repo/shorty.py
